### ISSUE TITLE
is it possible to add location of the car?

### ISSUE THREAD

**Issue by siobhanellis** [WonkiDonk/homebridge-jlr-incontrol#19]
Is it possible to provide the car location?

Longitude/Latitude would be very cool.

**Comment by william-cowell-mf** [comment]
I could provide this data as text under the vehicle info. However, iOS HoneKit does not provide an API for exposing location data via the Home app, so it's not really feasible.

I could look to implement something separately and integrate it with the Find My app, but that wouldn't be powered by Homebridge or HomeKit...

**Comment by siobhanellis** [comment]
It may be worth looking at one of the plugins that gives you the position of the sun. I can't remember how they did that.

**Comment by WonkiDonk** [comment]
Won't be supported on this version. Please watch [homebridge-jlr-remote](https://github.com/WonkiDonk/homebridge-jlr-remote).
