### ISSUE TITLE
Lock status not accurate 

### ISSUE THREAD

**Issue by eckline** [WonkiDonk/homebridge-jlr-incontrol#20]
Loving the plugin for homekit! I noticed that when going into the “home” app, it shows the vehicle is unlocked, when in reality it is locked. I then go into the Land Rover remote app and see it’s locked. I go back into the home app, and it updates automatically to locked.  

Outside of the lock status sometimes not being accurate, I am able to lock/unlock via home app.

**Comment by siobhanellis** [comment]
just confirming I have seen the same thing.

**Comment by william-cowell-mf** [comment]
This plug-in is being replaced by homebridge-JLR-remote, which addresses this issue and more.

**Comment by eckline** [comment]
> This plug-in is being replaced by homebridge-JLR-remote, which addresses this issue and more.

Where do I download that at?
