### ISSUE TITLE
Is it possible to add Tyres pressures?

### ISSUE THREAD

**Issue by siobhanellis** [WonkiDonk/homebridge-jlr-incontrol#21]
Is it possible to add Tyre Pressures?

I'm Beta testing myPace on iOS and it shows those.

**Comment by william-cowell-mf** [comment]
I definitely have access to the tyre pressure data. I just don't think Apple provide an endpoint in their HomeKit API that understands this type of data. I'll take a look though.

It won't get done in this plug-in, however. This plug-in is being replaced by homebridge-JLR-remote, which addresses a number of issues.

**Comment by siobhanellis** [comment]
It might be worth looking at what Eve have done with their Weather station. Apparently there are extensions that you can define yourself. It would be cool if it worked with the Eve App.

**Comment by siobhanellis** [comment]
> I definitely have access to the tyre pressure data. I just don't think Apple provide an endpoint in their HomeKit API that understands this type of data. I'll take a look though.
> 
> It won't get done in this plug-in, however. This plug-in is being replaced by homebridge-JLR-remote, which addresses a number of issues.

Hi William, any news on the new homebridge plugin for JLR.

Thanks.

**Comment by WonkiDonk** [comment]
Won't be supported on this version. Please watch [homebridge-jlr-remote](https://github.com/WonkiDonk/homebridge-jlr-remote).
