### ISSUE TITLE
Is it possible to show Charge Level as a separate tile?

### ISSUE THREAD

**Issue by AbuDhabiDude** [WonkiDonk/homebridge-jlr-incontrol#22]
Hi. At the moment, Battery level is only viewable by going into the car settings page. Would it be possible to set it as a separate item (and set the type as a sensor)? That way, it could appear as a tile in the status bar at the top of Homekit, but also it would be possible to create automations based on SOC. For example, if you want to stop your charging when the battery gets to 80% you would be able to create an automation for that. Some sensors won't register with Apple Homekit for automations, but the Eve app can generally create automations based on rising and falling figures (such as "when the garage temperature falls below 10 degrees, turn on the garage heater"), which are then integrated into Homekit. It's a bit cumbersome but it works! However, the battery would have to be set as the right kind of sensor for this to work. I hope thyat makes sense to you!

**Comment by william-cowell-mf** [comment]
This is a feature of HomeKit already. You can go into the tile and select "Show as Separate Tiles"

**Comment by AbuDhabiDude** [comment]
> This is a feature of HomeKit already. You can go into the tile and select "Show as Separate Tiles"

Yes but that doesn’t separate out the state of charge level as a separate tile. It separates out the preconditioning, the charger and the door locks. But the battery charge remains hidden.

**Comment by william-cowell-mf** [comment]
I believe that charge level is an attribute that has to be associated with another service. I don't think there's anything that can be done about that; it's a limitation of the HomeKit API.
