### ISSUE TITLE
Precondition not working. Gasoline range rover velar

### ISSUE THREAD

**Issue by allanjeevan** [WonkiDonk/homebridge-jlr-incontrol#26]

**Comment by jagpreetbatth** [comment]
Bump

Same issue.. can lock and unlock in HomeKit but can not precondition. Temperature can be changed in home app to heat, cool and auto as well as temperature change gauge changes but this information won't transmit to vehicle.

Did you ever find a solution?

**Comment by william-cowell-mf** [comment]
Not supported by this version of the plug-in. This version of the plug-in was only ever intended for EVs.
