### ISSUE TITLE
HOOBS 4.2.8 and jar 0.7 not working

### ISSUE THREAD

**Issue by kpejman** [WonkiDonk/homebridge-jlr-incontrol#31]
Hi, I recently upgraded to HOOBS 4.2.8. when I was in Hoobs 3.3.5, the values were showing up in the gui.
now I did a brand new install if Hoobs 4.2.8 but when I install the JLR adding, it won't work.
use the exact same config that was working in 3.3.5.

can you please help ?

**Comment by WonkiDonk** [comment]
Won't be supported on this version. Please watch [homebridge-jlr-remote](https://github.com/WonkiDonk/homebridge-jlr-remote).
