### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Mx-Razvan** [WonkiDonk/homebridge-jlr-incontrol#7]
Hi,

it seems that after the incontrol last update the plugin isn't working anymore. Any ideas?
Also - it would be possible to expose the fuel level instead of charging state?

Thanks<

R

**Comment by wakkoroti** [comment]
Looks like JLR changed all the URLs. Been poking in the index.js to change them and was able to get it to authenticate but not actually post a status yet. Blergh. Here are the new URLs though

IFAS_BASE_URL = "https://ifas.prod-row.jlrmotor.com/ifas/jlr"
IFOP_BASE_URL = "https://ifop.prod-row.jlrmotor.com/ifop/jlr"
IF9_BASE_URL = "https://if9.prod-row.jlrmotor.com/if9/jlr"

Maybe this also needs to be appended to the status call but not sure where that applies in the code here:

'status?includeInactive=true'

**Comment by Mx-Razvan** [comment]
Thanks for the feedback. I will play with it and see what will happen

**Comment by wakkoroti** [comment]
Got it to work by replacing the URLs and then changing some of the header versions. I left the header version at v2 for health status to get around it needing the status?includeInactive=true. Attaching index.js that I edited at /usr/local/lib/node_modules/homebridge-jlr-incontrol/dist. Rename to .js from .txt
[index.txt](https://github.com/WonkiDonk/homebridge-jlr-incontrol/files/4894439/index.txt)

**Comment by Mx-Razvan** [comment]
Thanks! I will try these days. 
What about exposing the fuel level instead of charging state? Any ideas? I'm looking over some JLR api docs but somehow they seems incomplete.

Many thanks,

R

**Comment by bluntiless** [comment]
Thanks @wakkoroti for the information regarding the new URL'S. I replaced the index.js file with the updated URL'S and it started working again immediately! Thanks again.

**Comment by william-cowell-mf** [comment]
FYI I've updated the plug-in with the updated URLs. Thanks.

**Comment by WonkiDonk** [comment]
Fix is included in v0.4.0
