### ISSUE TITLE
Preconditioning and gasoline level

### ISSUE THREAD

**Issue by allanjeevan** [WonkiDonk/homebridge-jlr-incontrol#8]
Hello sir,

I just tried installing the plugin and replaced the index file with new urls but the preconditioning isnt working and kindly can you add gasoline level insted of charger as i own a gasoline car. 

Thank you

**Comment by WonkiDonk** [comment]
Fixed in v0.6

**Comment by allanjeevan** [comment]
Well i tried but the preconditioning isnt still working... Thank you

**Comment by jagpreetbatth** [comment]
bump
